//Global Variables
var buttons=[
    "button#b0","button#b1","button#b2",
    "button#b3","button#b4","button#b5",
    "button#b6","button#b7","button#b8"
];                           //Array of game board button selectors
var restart=".start-button"; //start button selector
var ms=250;                  //Delay period in ms
var doing_something=1;       //Variable to deactivate buttons when displaying patterns
var gameover=0;              //Variable to indicate game over
var lvl=1;                   //Game Level
var entered_seq=[];          //Array of user entered sequence
var seq=[];                  //Array of sequence generated by computer
var audi=[
    "assets/audi_0.mp3","assets/audi_0.mp3","assets/audi_0.mp3",
    "assets/audi_0.mp3","assets/audi_0.mp3","assets/audi_0.mp3",
    "assets/audi_0.mp3","assets/audi_0.mp3","assets/audi_0.mp3"
];    //button audio ques
var audi_win="assets/audi_win.mp3";    //level up audio que
var audi_lose="assets/audi_lost.mp3";    //lost audio que

$('h2').text("Click Start to Begin");    //Ask user to start game

/*------------------------------------Button Glowers-----------------------------------------------------------*/

//button glown when showing sequence(maybe yellow)
function glow(button){
    $(button).toggleClass('clicked');
    setTimeout(function(){$(button).toggleClass('clicked');},ms);
}

//butten glown to indicate correct move(maybe orange)
function glow_right(button){
    $(button).toggleClass('clicked-right');
    setTimeout(function(){$(button).toggleClass('clicked-right');},ms);
}

//butten glown to indicate wrong move(maybe red)
function glow_wrong(button){
    $(button).toggleClass('clicked-wrong');
    setTimeout(function(){$(button).toggleClass('clicked-wrong');},ms);
}

//butten glown to indicate wrong move(maybe red)
function flasher(txt){
    $(txt).fadeOut(40).fadeIn(40).fadeOut(40).fadeIn(40);
}

/*----------------------------------Level up or Game Over------------------------------------------------------*/

//end game if sequence not enterred correctly
function end_game(){
    new Audio(audi_lose).play();
    flasher("h2");
    $('h2').text("Max Lvl "+(lvl-1)+". Game Over! Please Start over");
    lvl=1;
    seq=[];
    entered_seq=[];
    doing_something=1;
    gameover=1;
}

//level up when level is completed sucessfully
function level_up(){
    new Audio(audi_win).play();
    lvl+=1;
    flasher("h2");
    $('h2').text("Level:"+lvl);
    seq=[];
    entered_seq=[];
    setTimeout(seq_generator(lvl),ms*2);
}
/*---------------------------Generate and Display Sequence-----------------------------------------------------*/

//Generate random sequence based on level
function seq_generator(lvl){
    doing_something=1;
    seq=[];
    for(i=0;i<lvl;i++){
        seq.push(Math.floor(Math.random()*9));
    }
    seq_display(seq,0);
}

//Display sequence sequentially using recursion
function seq_display(seq,n){
    glow(buttons[seq[n]]);
    if(n==seq.length){
        doing_something=0;
    }
    else{
        setTimeout(function(){seq_display(seq,n+1);},ms*2);
    }
}

/*--------------------------Button Event Listeners-------------------------------------------------------------*/

//Game board buttons listener
for(i=0;i<buttons.length;i++){
    $(buttons[i]).click(function(){
        if(doing_something){
            //button deactivated when displaying sequence
        }
        else{
            if('vibrate'in navigator){
                navigator.vibrate(100);
            }
            entered_seq.push(parseInt(this.id.slice(1)));
            new Audio(audi[parseInt(this.id.slice(1))]).play();
            for(i=0;i<entered_seq.length;i++){
                if(entered_seq[i]!=seq[i]){
                    glow_wrong(this);
                    end_game();
                }
            }
            if(!gameover){
                glow_right(this);
                if(seq.length==entered_seq.length){setTimeout(level_up,ms*2);}
            }
        }
    });
}

//Start button listener
$(restart).click(function(){
        entered_seq=[];
        seq=[];
        gameover=0;
        lvl=1;
        $('h2').text("Level:"+lvl);
        setTimeout(seq_generator(lvl),ms*2);
});

/*------------------------------------------------------------------------------------------------------------*/
